spring.application.name=sucursal
server.port=8081
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_-udnOJOD-NdgPSKEJxI@perfulandiasql-duocuc-6516.g.aivencloud.com:26444/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_-udnOJOD-NdgPSKEJxI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# URL del servidor Eureka (suponiendo que corre en localhost:8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Registro y descubrimiento
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Activar logs de Feign para debug
logging.level.feign=DEBUG
logging.level.cl.perfulandia=DEBUG
